version: '3'
services:
  es-node1:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    container_name: es-node1
    environment:
      - cluster.name=es-cluster
      - node.name=es-node1
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - es-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - es-net
  es-node2:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    container_name: es-node2
    environment:
      - cluster.name=es-cluster
      - node.name=es-node2
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data2:/usr/share/elasticsearch/data
    networks:
      - es-net
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.13.2
    container_name: es-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://es-node1:9200
      ELASTICSEARCH_HOSTS: https://es-node1:9200
    networks:
      - es-net

volumes:
  es-data1:
  es-data2:

networks:
  es-net: