tf-init:
	docker-compose -f docker-compose.yml run --rm terraform init

tf-plan:
	docker-compose -f docker-compose.yml run --rm terraform plan

tf-apply:
	docker-compose -f docker-compose.yml run --rm terraform apply
